# Language code mapping
LANGUAGE_MAP = {
    "Afrikaans (Afrikaans)": "af",
    "Albanian (Shqip)": "sq",
    "Amharic (አማርኛ)": "am",
    "Arabic (العربية)": "ar",
    "Armenian (Հայերեն)": "hy",
    "Azerbaijani (Azərbaycanca)": "az",
    "Basque (Euskara)": "eu",
    "Belarusian (Беларуская)": "be",
    "Bengali (বাংলা)": "bn",
    "Bosnian (Bosanski)": "bs",
    "Bulgarian (Български)": "bg",
    "Catalan (Català)": "ca",
    "Cebuano (Cebuano)": "ceb",
    "Chichewa (Chichewa)": "ny",
    "Chinese (中文)": "zh",
    "Corsican (Corsu)": "co",
    "Croatian (Hrvatski)": "hr",
    "Czech (Čeština)": "cs",
    "Danish (Dansk)": "da",
    "Dutch (Nederlands)": "nl",
    "English (English)": "en",
    "Esperanto (Esperanto)": "eo",
    "Estonian (Eesti)": "et",
    "Filipino (Filipino)": "tl",
    "Finnish (Suomi)": "fi",
    "French (Français)": "fr",
    "Galician (Galego)": "gl",
    "Georgian (ქართული)": "ka",
    "German (Deutsch)": "de",
    "Greek (Ελληνικά)": "el",
    "Gujarati (ગુજરાતી)": "gu",
    "Haitian Creole (Kreyòl Ayisyen)": "ht",
    "Hausa (Hausa)": "ha",
    "Hawaiian (Ōlelo Hawaii)": "haw",
    "Hebrew (עברית)": "iw",
    "Hindi (हिन्दी)": "hi",
    "Hmong (Hmoob)": "hmn",
    "Hungarian (Magyar)": "hu",
    "Icelandic (Íslenska)": "is",
    "Igbo (Asụsụ Igbo)": "ig",
    "Indonesian (Bahasa Indonesia)": "id",
    "Irish (Gaeilge)": "ga",
    "Italian (Italiano)": "it",
    "Japanese (日本語)": "ja",
    "Javanese (Basa Jawa)": "jv",
    "Kannada (ಕನ್ನಡ)": "kn",
    "Kazakh (Қазақ тілі)": "kk",
    "Khmer (ភាសាខ្មែរ)": "km",
    "Korean (한국어)": "ko",
    "Kurdish (Kurdî)": "ku",
    "Kyrgyz (Кыргызча)": "ky",
    "Lao (ລາວ)": "lo",
    "Latin (Latina)": "la",
    "Latvian (Latviešu)": "lv",
    "Lithuanian (Lietuvių)": "lt",
    "Luxembourgish (Lëtzebuergesch)": "lb",
    "Macedonian (Македонски)": "mk",
    "Malagasy (Malagasy)": "mg",
    "Malay (Bahasa Melayu)": "ms",
    "Malayalam (മലയാളം)": "ml",
    "Maltese (Malti)": "mt",
    "Maori (Māori)": "mi",
    "Marathi (मराठी)": "mr",
    "Mongolian (Монгол)": "mn",
    "Myanmar (မြန်မာ)": "my",
    "Nepali (नेपाली)": "ne",
    "Norwegian (Norsk)": "no",
    "Odia (ଓଡ଼ିଆ)": "or",
    "Pashto (پښتو)": "ps",
    "Persian (فارسی)": "fa",
    "Polish (Polski)": "pl",
    "Portuguese (Português)": "pt",
    "Punjabi (ਪੰਜਾਬੀ)": "pa",
    "Romanian (Română)": "ro",
    "Russian (Русский)": "ru",
    "Samoan (Gagana Samoa)": "sm",
    "Scottish Gaelic (Gàidhlig)": "gd",
    "Serbian (Српски)": "sr",
    "Sesotho (Sesotho)": "st",
    "Shona (ChiShona)": "sn",
    "Sindhi (سنڌي)": "sd",
    "Sinhala (සිංහල)": "si",
    "Slovak (Slovenčina)": "sk",
    "Slovenian (Slovenščina)": "sl",
    "Somali (Soomaali)": "so",
    "Spanish (Español)": "es",
    "Sundanese (Basa Sunda)": "su",
    "Swahili (Kiswahili)": "sw",
    "Swedish (Svenska)": "sv",
    "Tajik (Тоҷикӣ)": "tg",
    "Tamil (தமிழ்)": "ta",
    "Tatar (Татарча)": "tt",
    "Telugu (తెలుగు)": "te",
    "Thai (ไทย)": "th",
    "Turkish (Türkçe)": "tr",
    "Turkmen (Türkmençe)": "tk",
    "Ukrainian (Українська)": "uk",
    "Urdu (اُردُو)": "ur",
    "Uyghur (ئۇيغۇرچە)": "ug",
    "Uzbek (Ozbek)": "uz",
    "Vietnamese (Tiếng Việt)": "vi",
    "Welsh (Cymraeg)": "cy",
    "Xhosa (isiXhosa)": "xh",
    "Yiddish (ייִדיש)": "yi",
    "Yoruba (Yorùbá)": "yo",
    "Zulu (isiZulu)": "zu"
}


def get_language_code(language_name):
    return LANGUAGE_MAP.get(language_name, "en")
